import type { TroubleshootingEntry } from './types'

/** Common problems, in the order people usually meet them. */
export const TROUBLESHOOTING: TroubleshootingEntry[] = [
  {
    id: 'device-wont-connect',
    problem: 'My phone will not connect',
    why: 'The phone is offline, WhatsApp removed the link, or the connection dropped and is waiting to retry.',
    steps: [
      'Check that the phone is switched on and has internet. Open WhatsApp on it once.',
      'On the Devices screen, click Reconnect on the card and wait up to a minute.',
      'If the card says "Logged out", the link was removed on the phone. Click "+ Add Device" and link it again.',
      'If a red message shows on the card, read it: it says what went wrong.',
      'Still stuck? Restart RapBooster, then export diagnostics and contact support.',
    ],
    related: ['devices'],
  },
  {
    id: 'qr-expired',
    problem: 'The QR code expired or will not scan',
    why: 'WhatsApp changes the QR code every 20 seconds or so, and stops after a few tries if nobody scans it.',
    steps: [
      'Close the "Add WhatsApp Device" window.',
      'Click "+ Add Device" again and click "Generate QR & Connect". Have your phone ready first.',
      'On the phone, go to WhatsApp, then Settings, then "Linked Devices", then "Link a Device", and scan straight away.',
      'Hold the phone steady about 20 cm from the screen. Make the window larger if the code is small.',
      'If scanning keeps failing, use the "Pairing code" tab instead.',
    ],
    related: ['devices'],
  },
  {
    id: 'not-sending',
    problem: 'My campaign is running but nothing is being sent',
    why: 'RapBooster is holding messages back on purpose to protect your numbers, or no phone can send right now.',
    steps: [
      'Quiet hours: check the time. Campaigns pause during quiet hours and carry on when they end (Settings › Sending & safety).',
      'Daily cap: open Devices. A full usage bar means the phone reached its limit. Sending carries on tomorrow.',
      'Warmup: a number in warmup has a lower limit for its first ten days.',
      'Safety pause: a card that says "Paused for safety" stopped because of failures. Read why before clicking "Resume now".',
      'Connection: the campaign needs at least one of its chosen phones to be Connected.',
    ],
    related: ['campaigns', 'devices', 'settings-sending'],
  },
  {
    id: 'skipped',
    problem: 'Some people were skipped',
    why: 'Skipped messages were left out on purpose, never by mistake.',
    steps: [
      "Open the campaign's Recipients and choose Skipped.",
      'Read the "Error / reason" column.',
      '"Opted out" means the person asked not to be messaged. Respect it.',
      'A number not on WhatsApp cannot receive messages. Use "Verify numbers" on the Contacts screen to clean your lists.',
    ],
    related: ['campaigns', 'contacts'],
  },
  {
    id: 'failed',
    problem: 'Many messages failed',
    why: 'Usually wrong numbers, numbers not on WhatsApp, a lost connection, or WhatsApp limiting your number.',
    steps: [
      'Pause the campaign.',
      'Open Recipients, choose Failed, and read the reasons.',
      'Wrong or short numbers: check the country code in your list and import again.',
      'Not on WhatsApp: tick "Skip numbers not on WhatsApp" in your next campaign.',
      'If failures started suddenly on one phone, read "My account got a warning" below before sending more.',
    ],
    related: ['campaigns', 'contacts', 'devices'],
  },
  {
    id: 'ban-risk',
    problem: 'My account got a warning, or I am worried about a ban',
    why: 'WhatsApp restricts numbers that send too many messages, send too fast, or get blocked and reported by people who did not expect them.',
    steps: [
      'Stop or pause every campaign on that number at once.',
      'Do not log out and link again over and over. Let the number rest for a few days.',
      'Lower the daily cap in Settings › Sending & safety, and switch on Warmup for that number.',
      'Only message people who agreed to hear from you, and honour every opt-out.',
      'Use spintax and merge tags so messages are not identical, and keep the random delays.',
    ],
    related: ['settings-sending', 'devices', 'templates'],
  },
  {
    id: 'hidden-number',
    problem: 'A contact shows "Number hidden by WhatsApp"',
    why: 'WhatsApp sometimes shares only a private ID instead of the phone number, especially in groups and for people who are not saved in your phone.',
    steps: [
      'You can still read and reply to their chat in the Inbox as usual.',
      'Wait: as soon as WhatsApp reveals the number, RapBooster replaces it everywhere by itself.',
      'If you already had a chat with that number, the two chats are merged into one.',
      'A STOP from this person is honoured straight away, like any other opt-out.',
      'Hidden numbers are never exported or added to campaigns, because there is no real number to send to.',
    ],
    related: ['inbox', 'groups'],
  },
  {
    id: 'ai-key',
    problem: 'The AI bot does not answer or says the key is wrong',
    why: 'The key was mistyped, has no credit left, belongs to another provider, or a reply limit was reached.',
    steps: [
      'Open AI Bot and check the Provider matches the company your key came from.',
      'Paste the key again, click "Save key", then "Test key".',
      "If the test fails, log in to the AI company's website and check that your account has credit.",
      'Check "Enable Auto-Replies" is ticked and the daily reply limits are not used up (see the Usage panel).',
      'Check the chat is not escalated, opted out or a group. The bot never answers those.',
    ],
    related: ['chatbot'],
  },
  {
    id: 'import-problems',
    problem: 'My contacts will not import',
    why: 'The file type is not supported, or the columns or numbers are not in the expected shape.',
    steps: [
      'Use a .csv, .xlsx or .vcf file. Save old .xls files as .xlsx first.',
      'Make sure the first row has column names, such as Name and Phone.',
      'Map one column to Mobile.',
      'Answer the country code question. Numbers without a country code are reported as invalid.',
      'Open the error report in your exports folder to see which rows failed and why.',
    ],
    related: ['contacts'],
  },
  {
    id: 'app-closed',
    problem: 'Nothing was sent while my computer was off',
    why: 'RapBooster sends from this computer. When it is closed or the computer is asleep, everything waits.',
    steps: [
      'Keep RapBooster running while campaigns run. Closing the window can leave it running in the tray (Settings › Desktop).',
      'Switch on "Start RapBooster when the computer starts" so it carries on after a restart.',
      'When you open it again, waiting campaigns, sequences and scheduled messages carry on by themselves.',
    ],
    related: ['settings-desktop'],
  },
  {
    id: 'diagnostics',
    problem: 'How do I send diagnostics to support?',
    why: 'A diagnostics file lets support see what happened without seeing your messages.',
    steps: [
      'Open Settings and find "Data & diagnostics", or open Help Center and find "Contact support".',
      'Click "Export diagnostics". The folder with the file opens.',
      'Send that file to support with a short description of the problem and when it happened.',
      'The file has no message content, and phone numbers and keys are hidden.',
    ],
    related: ['settings-diagnostics', 'help'],
  },
]
